# Generated by Django 4.1 on 2023-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='document')),
                ('user', models.CharField(max_length=255)),
                ('student', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
