# Generated by Django 4.1 on 2023-06-28 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_document_id_document_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ids',
            field=models.AutoField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
    ]
